name: Update Major Release Tag

# Reusable workflow files must be in `.github/workflows/`. While it would be
# easier to find this definition if it were at the root of the project, GitHub
# Actions does not support running workflows from there.
# <https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows#calling-a-reusable-workflow>

on:
  workflow_call:
  release:
    types: [published]

# Note this doesn't grant the `contents: write` permission: the calling workflow
# must do that. Document the need for it (& give up extra permissions the caller
# may have granted unnecessarily).
# <https://docs.github.com/en/actions/reference/workflows-and-actions/reusing-workflow-configurations#supported-keywords-for-jobs-that-call-a-reusable-workflow>
permissions:
  # Retain permission to push tags.
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Update major version tag 
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        MAJOR=${VERSION%%.*}
        echo "Tagging major version $MAJOR ($VERSION)"
        git config --global user.name "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.email "github-actions[bot]"
        git tag -fa ${MAJOR} -m "Update major version $MAJOR to $VERSION"
        git push origin ${MAJOR} --force
